### ISSUE TITLE
Blows up immediately when installed

### ISSUE THREAD

**Issue by matthewdeanmartin** [darrenburns/kupo#1]
This happens to be in a bash console in windows and was installed by pipx using python 3.11. I'm not sure any of those are relevant, this looks like a basic bug/library compatibility issue.

```
$ pipx install kupo
creating virtual environment...
installing kupo...
done!
  installed package kupo 0.1.0a0, installed using Python 3.11.1
  These apps are now globally available
    - kupo.exe

matth@lenovo MINGW64 ~
$ kupo
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\matth\.local\bin\kupo.exe\__main__.py", line 7, in <module>
  File "C:\Users\matth\.local\pipx\venvs\kupo\Lib\site-packages\kupo\app.py", line 384, in run
    FilesApp.run(css_file=directory / "kupo.css")
  File "C:\Users\matth\.local\pipx\venvs\kupo\Lib\site-packages\textual\app.py", line 206, in run
    asyncio.run(run_app())
  File "C:\Users\matth\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\matth\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\matth\.local\pipx\venvs\kupo\Lib\site-packages\textual\app.py", line 203, in run_app
    app = cls(screen=screen, driver_class=driver, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: App.__init__() got an unexpected keyword argument 'css_file'
```

**Comment by darrenburns** [comment]
Yeah - this isn't yet ready to be installed (see warning on readme). It's a hobby project that I sometimes commit time to, but when it's ready I'll add installation instructions to the readme.
