### ISSUE TITLE
Won't build on Python 3.12.  Remove lock files and rebuild fixes. 

### ISSUE THREAD

**Issue by ssteinerx** [darrenburns/kupo#3]
The specific version soup specified in `poetry.lock`  result in a version hunt on aiohttp that fails:

```
...
- Downgrading aiohttp (3.9.5 -> 3.8.5): Failed

...lots of compiler warnings and a few hard errors trying to build 3.8.5
 ```

Kill the lock files and `poetry install` and it figures it out.

I didn't go any deeper into *why*; doesn't seem important.

**Comment by slavaGanzin** [comment]
```python
Traceback (most recent call last):
  File "/Users/slava/.asdf/installs/python/3.12.4/bin/kupo", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/slava/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/kupo/app.py", line 384, in run
    FilesApp.run(css_file=directory / "kupo.css")
  File "/Users/slava/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/textual/app.py", line 206, in run
    asyncio.run(run_app())
  File "/Users/slava/.asdf/installs/python/3.12.4/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/slava/.asdf/installs/python/3.12.4/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.asdf/installs/python/3.12.4/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/slava/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/textual/app.py", line 203, in run_app
    app = cls(screen=screen, driver_class=driver, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: App.__init__() got an unexpected keyword argument 'css_file'
```
